# Disable dynamic pointer acceleration for all mice.
input type:pointer {
    accel_profile flat
}

# Use the same acceleration-free profile for the touchpad.
input type:touchpad {
    accel_profile flat
    tap enabled
    tap_button_map lrm
}
